# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://redistogo:f9cb7fb04998a52c91c73ca6ec247719@slimehead.redistogo.com:9339/

development:
  adapter: async

test:
  adapter: async
